### PR TITLE
chore!: use prettier-plugin-pkg and yarn, prefer `prettierrc` or its defaults by default

### LINKED ISSUE #58: Prefer `prettier` configuration instead options from this plugin only
A `.prettierrc` file would be used constantly for all tools

### PR DESCRIPTION
**Pull request by JounQin**
BREAKING: prefer `prettierrc` or its defaults by default

close #58

### CODE REVIEW

**Comment by JounQin** [comment]
Besides, do you think collaboration on this repo would be useful too?

**Review by ota-meshi — APPROVED** [review]
Thank you!

**Comment by ota-meshi** [comment]
> Besides, do you think collaboration on this repo would be useful too?

This project is a personal project dedicated to the project I manage, so I don't think collaborating is useful for now 😄

**Comment by JounQin** [comment]
Never mind.

**Pull request merged**
